// <auto-generated />
using EquiApi.Persistence.Util;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EquiApi.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260523133955_newMigs")]
    partial class newMigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("EquiPressure")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquiApi.Persistence.Model.AccountRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccountRole", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<int?>("HouseNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Address", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Breed", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PLZ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PLZ", "Name");

                    b.ToTable("City", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.DeviceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumOfAllowedPeople")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DeviceCategory", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.DeviceUser", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("DeviceId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("DeviceUser", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Horse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<LocalDate>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Name");

                    b.ToTable("Horse", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.HorseBreed", b =>
                {
                    b.Property<int>("HorseId")
                        .HasColumnType("integer");

                    b.Property<int>("BreedId")
                        .HasColumnType("integer");

                    b.HasKey("HorseId", "BreedId");

                    b.HasIndex("BreedId");

                    b.ToTable("HorseBreed", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Hand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("GroupId", "Pace", "Hand")
                        .IsUnique();

                    b.ToTable("Measurement", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.MeasurementData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MeasurementId")
                        .HasColumnType("integer");

                    b.Property<Instant>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId");

                    b.ToTable("MeasurementData", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.MeasurementDevice", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId");

                    b.ToTable("MeasurementDevice", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.MeasurementEligibility", b =>
                {
                    b.Property<int>("MeasurementGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer");

                    b.HasKey("MeasurementGroupId", "ReleaseId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("MeasurementEligibility", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.MeasurementGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<LocalDate>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HorseId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("SaddleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("HorseId");

                    b.HasIndex("PersonId");

                    b.HasIndex("SaddleId");

                    b.ToTable("MeasurementGroup", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<LocalDate>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebsiteLink")
                        .HasColumnType("text");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("DateOfBirth");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("Person", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.PersonHorse", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("HorseId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");

                    b.HasKey("PersonId", "HorseId");

                    b.HasIndex("HorseId");

                    b.ToTable("PersonHorse", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.PersonRelationship", b =>
                {
                    b.Property<int>("EquestrianId")
                        .HasColumnType("integer");

                    b.Property<int>("SaddlerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsContact")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("boolean");

                    b.HasKey("EquestrianId", "SaddlerId");

                    b.HasIndex("SaddlerId");

                    b.ToTable("PersonRelationship", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.PersonRoleAssignment", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("PersonId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("PersonRoleAssignment", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Release", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<Instant>("ReleaseTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Release", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Rocket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MaxThrust")
                        .HasColumnType("double precision");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PayloadDeltaV")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Rocket", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Saddle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("HorseId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("HorseId");

                    b.ToTable("Saddle", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.SaddleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SaddleCategory", "EquiPressure");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Address", b =>
                {
                    b.HasOne("EquiApi.Persistence.Model.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.DeviceUser", b =>
                {
                    b.HasOne("EquiApi.Persistence.Model.MeasurementDevice", "Device")
                        .WithMany("Users")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquiApi.Persistence.Model.Person", "User")
                        .WithMany("UserDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Horse", b =>
                {
                    b.HasOne("EquiApi.Persistence.Model.Address", "Address")
                        .WithMany("Horses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.HorseBreed", b =>
                {
                    b.HasOne("EquiApi.Persistence.Model.Breed", "Breed")
                        .WithMany("HorseBreeds")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquiApi.Persistence.Model.Horse", "Horse")
                        .WithMany("HorseBreeds")
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breed");

                    b.Navigation("Horse");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Measurement", b =>
                {
                    b.HasOne("EquiApi.Persistence.Model.MeasurementGroup", "Group")
                        .WithMany("Measurements")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.MeasurementData", b =>
                {
                    b.HasOne("EquiApi.Persistence.Model.Measurement", "Measurement")
                        .WithMany("MeasurementDates")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.MeasurementDevice", b =>
                {
                    b.HasOne("EquiApi.Persistence.Model.DeviceCategory", "Category")
                        .WithMany("Devices")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquiApi.Persistence.Model.Person", "Owner")
                        .WithMany("OwnerDevices")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.MeasurementEligibility", b =>
                {
                    b.HasOne("EquiApi.Persistence.Model.MeasurementGroup", "MeasurementGroup")
                        .WithMany("MeasurementEligibilities")
                        .HasForeignKey("MeasurementGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquiApi.Persistence.Model.Release", "Release")
                        .WithMany("MeasurementEligibilities")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementGroup");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.MeasurementGroup", b =>
                {
                    b.HasOne("EquiApi.Persistence.Model.MeasurementDevice", "Device")
                        .WithMany("MeasurementGroups")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquiApi.Persistence.Model.Horse", "Horse")
                        .WithMany("MeasurementGroups")
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquiApi.Persistence.Model.Person", "Person")
                        .WithMany("MeasurementGroups")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquiApi.Persistence.Model.Saddle", "Saddle")
                        .WithMany("MeasurementGroups")
                        .HasForeignKey("SaddleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Horse");

                    b.Navigation("Person");

                    b.Navigation("Saddle");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Person", b =>
                {
                    b.HasOne("EquiApi.Persistence.Model.Address", "Address")
                        .WithMany("Persons")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.PersonHorse", b =>
                {
                    b.HasOne("EquiApi.Persistence.Model.Horse", "Horse")
                        .WithMany("Persons")
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquiApi.Persistence.Model.Person", "Person")
                        .WithMany("Horses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.PersonRelationship", b =>
                {
                    b.HasOne("EquiApi.Persistence.Model.Person", "Equestrian")
                        .WithMany()
                        .HasForeignKey("EquestrianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquiApi.Persistence.Model.Person", "Saddler")
                        .WithMany("Relationships")
                        .HasForeignKey("SaddlerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equestrian");

                    b.Navigation("Saddler");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.PersonRoleAssignment", b =>
                {
                    b.HasOne("EquiApi.Persistence.Model.Person", "Person")
                        .WithMany("Roles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquiApi.Persistence.Model.AccountRole", "Role")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Release", b =>
                {
                    b.HasOne("EquiApi.Persistence.Model.Person", "Person")
                        .WithMany("Releases")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Saddle", b =>
                {
                    b.HasOne("EquiApi.Persistence.Model.SaddleCategory", "Category")
                        .WithMany("Saddles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquiApi.Persistence.Model.Horse", "Horse")
                        .WithMany("Saddles")
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Horse");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.AccountRole", b =>
                {
                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Address", b =>
                {
                    b.Navigation("Horses");

                    b.Navigation("Persons");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Breed", b =>
                {
                    b.Navigation("HorseBreeds");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.DeviceCategory", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Horse", b =>
                {
                    b.Navigation("HorseBreeds");

                    b.Navigation("MeasurementGroups");

                    b.Navigation("Persons");

                    b.Navigation("Saddles");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Measurement", b =>
                {
                    b.Navigation("MeasurementDates");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.MeasurementDevice", b =>
                {
                    b.Navigation("MeasurementGroups");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.MeasurementGroup", b =>
                {
                    b.Navigation("MeasurementEligibilities");

                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Person", b =>
                {
                    b.Navigation("Horses");

                    b.Navigation("MeasurementGroups");

                    b.Navigation("OwnerDevices");

                    b.Navigation("Relationships");

                    b.Navigation("Releases");

                    b.Navigation("Roles");

                    b.Navigation("UserDevices");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Release", b =>
                {
                    b.Navigation("MeasurementEligibilities");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.Saddle", b =>
                {
                    b.Navigation("MeasurementGroups");
                });

            modelBuilder.Entity("EquiApi.Persistence.Model.SaddleCategory", b =>
                {
                    b.Navigation("Saddles");
                });
#pragma warning restore 612, 618
        }
    }
}
