= User Stories
Flora Dallinger, Katharina Einzenberger, Lena Graßauer, Lejla Music

. Als Reiter*in möchte ich selber Messungen mit dem Satteldruckmessgerät durchführen, um Sattler- und Tierarztkosten zu vermeiden.

. Als Reiter*in möchte ich für verschiedenen Gangarten Messungen durchführen, um zu sehen, oba das Problem nur in einer Gangart auftritt.

. Als Reiter*in möchte ich umliegende Sattler*innen in der App angezeigt bekommen, falls ich bei einer Messung bemerke, dass etwas nicht stimmt.

. Als Benutzer möchte ich meine Pferde in der App eintragen können und ihre Sattel anlegen, um einen Überblick über meine Tiere zu behalten.

. Als neuer Benutzer möchte ich mich mit vorhandenen Konten wie Google, Microsoft, Github etc anmelden, anstatt ein neues Konto zu erstellen, um Zeit und Mühen zu sparen.

. Als Benutzer möchte ich die vorhandenen Messungen eines Pferdes sehen, wenn ich es anklicke, um zu sehen wie lang die letze Messung her ist. 

. Als Benuter möchte ich den Start- und Endzeitpunkt der Messung selber bestimmen und nicht mit einer vorgegebenen Zeit durchführen, um Stress zu vermeiden.    

. Als Benutzer möchte ich den Besitzer des Pferdes eintragen, falls ich eine Reitbeteiligung habe, und beide Pferde denselben Namen haben.

. Als Messgerät-Besitzer*in möchte ich alle bei mir angelegten Reiter einsehen und löschen können, um mein Gerät für viele Leute zur Verfügung stellen zu können und auch um es verkaufen zu können. 

. Als Messgerät-Besitzer*in möchte ich mich mit meinem QR-Code anmelden, der mitgeliefert wird, und der mein Messgerät mit einer Seriennummer identifiziert. Diesen QR-Code möchte ich dann an Reiter*innen weitergeben



