<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.2"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime" Version="10.0.0"/>
        <PackageReference Include="OneOf" Version="3.0.271" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\EquiApi.Shared\EquiApi.Shared.csproj"/>
        <ProjectReference Include="..\EquiApi\EquiApi.csproj" />
    </ItemGroup>
</Project>
