<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\EquiApi.Core\EquiApi.Core.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="AwesomeAssertions" Version="9.6.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
        <PackageReference Include="NSubstitute" Version="6.2.0" />
        <PackageReference Include="xunit.v3" Version="4.0.1" />
        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <Using Include="AwesomeAssertions"/>
        <Using Include="Xunit"/>
    </ItemGroup>
</Project>
