@BaseUrl = http://localhost:5200/api

### Person Endpoints
@personId = 1
@saddlerId = 2
@equestrianId = 1

### 1. Person (Equestrian) abrufen
GET {{BaseUrl}}/persons/equestrians/{{personId}}

### 1.2 Person (Saddler) abrufen
GET {{BaseUrl}}/persons/equestrians/{{equestrianId}}/saddlers/{{saddlerId}}

### 2. Person abrufen (minimale Daten)
GET {{BaseUrl}}/persons/{{personId}}/profile-data

### 3. Adresse einer Person abrufen
GET {{BaseUrl}}/persons/{{personId}}/location

### 4. Kontakte einer Person abrufen
GET {{BaseUrl}}/persons/{{personId}}/contacts

### 5. Favoriten einer Person abrufen
GET {{BaseUrl}}/persons/{{personId}}/favourites

### 6. Alle Sattler mit Adresse (Person_Id, Name und location)
GET {{BaseUrl}}/persons/equestrians/{{equestrianId}}/saddlers/locations

### 7. Alle Pferde einer Person abrufen
GET {{BaseUrl}}/persons/{{personId}}/horses

### 8. Alle Geräte einer Person abrufen (inkl. Owner-Info)
GET {{BaseUrl}}/persons/{{personId}}/devices

### 9. Neue Person anlegen
POST {{BaseUrl}}/persons
Content-Type: application/json

{
    "firstName": "Max",
    "lastName": "Mustermann",
    "dateOfBirth": "1995-05-20",
    "email": "max@reiter.at",
    "addressId": 1
}

### 10. Person aktualisieren
PUT {{BaseUrl}}/persons/{{personId}}
Content-Type: application/json

{
    "id": {{personId}},
    "firstName": "Max",
    "lastName": "Mustermann-Update",
    "height": 182.0,
    "weight": 74.5,
    "dateOfBirth": "1995-05-20",
    "email": "max.neu@reiter.at",
    "addressId": 1
}

### 11. Person löschen
DELETE {{BaseUrl}}/persons/{{personId}}

### 12. Alle Pferde einer Person abrufen (mit PferdeId, Location und Profilbild einer Person)
GET {{BaseUrl}}/persons/{{personId}}/horses/locations

### 13. eine Location hinzufügen
POST {{BaseUrl}}/locations
Content-Type: application/json

{
    "street": "Hausstraße",
    "houseNumber": 12,
    "cityName": "Traun",
    "plz": "4050"
}

### 14. eine Location hinzufügen (strasse optional)
POST {{BaseUrl}}/locations
Content-Type: application/json

{
    "cityName": "Traun",
    "plz": "4050"
}
