@BaseUrl = http://localhost:5200/api

### Person Endpoints
@personId = 1
@saddlerId = 2
@equestrianId = 1

### 1. Person (Equestrian) abrufen
GET {{BaseUrl}}/persons/equestrians/{{personId}}

### 1.2 Person (Saddler) abrufen
GET {{BaseUrl}}/persons/saddlers/{{saddlerId}}

### 2. Person abrufen (minimale Daten)
GET {{BaseUrl}}/persons/{{personId}}/profile-data

### 3. Adresse einer Person abrufen
GET {{BaseUrl}}/persons/{{personId}}/location

### 4. Kontakte einer Person abrufen
GET {{BaseUrl}}/persons/{{personId}}/contacts

### 5. Favoriten einer Person abrufen
GET {{BaseUrl}}/persons/{{personId}}/favourites

### 6. Alle Sattler mit Adresse
GET {{BaseUrl}}/persons/saddlers

### 7. Alle Sattler Favoriten mit Adresse
GET {{BaseUrl}}/persons/equestrians/{{equestrianId}}/favourites

### 8. Alle Sattler Kontakte mit Adresse
GET {{BaseUrl}}/persons/equestrians/{{equestrianId}}/contacts

### 9. Alle Pferde einer Person abrufen
GET {{BaseUrl}}/persons/{{personId}}/horses

### 10. Alle Geräte einer Person abrufen (inkl. Owner-Info)
GET {{BaseUrl}}/persons/{{personId}}/devices

### 11. Neue Person anlegen
POST {{BaseUrl}}/persons
Content-Type: application/json

{
    "firstName": "Max",
    "lastName": "Mustermann",
    "dateOfBirth": "1995-05-20",
    "email": "max@reiter.at",
    "addressId": 1
}

### 12. Person aktualisieren
PATCH {{BaseUrl}}/persons/{{personId}}
Content-Type: application/json

{
    "firstName": "Max",
    "lastName": "Mustermann-Update",
    "height": 182.0
}

### 13. Person löschen
DELETE {{BaseUrl}}/persons/{{personId}}

### 14. Alle Pferde einer Person abrufen (mit PferdeId, Location und Profilbild einer Person)
GET {{BaseUrl}}/persons/{{personId}}/horses/locations

### 15. eine Location hinzufügen
POST {{BaseUrl}}/locations
Content-Type: application/json

{
    "street": "Hausstraße",
    "houseNumber": 12,
    "cityName": "Traun",
    "plz": "4050"
}

### 16. eine Location hinzufügen (strasse optional)
POST {{BaseUrl}}/locations
Content-Type: application/json

{
    "cityName": "Traun",
    "plz": "4050"
}


### 15. Alle Pferde eines users
GET {{BaseUrl}}/horses/1